// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHwhcbGKxovcSwuRnWawAGm8DekVDtrP4',
    appId: '1:42486479397:web:476cc6398733c2bf6f9dcc',
    messagingSenderId: '42486479397',
    projectId: 'smart-agri-7a6ed',
    authDomain: 'smart-agri-7a6ed.firebaseapp.com',
    storageBucket: 'smart-agri-7a6ed.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBewqGmy1nzrLbBPFwntwNKJvpFq-yjPck',
    appId: '1:42486479397:android:164c17fb1d1da90c6f9dcc',
    messagingSenderId: '42486479397',
    projectId: 'smart-agri-7a6ed',
    storageBucket: 'smart-agri-7a6ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDra81KEg99mb2lgaWB0YSY6rMUt8R52MU',
    appId: '1:42486479397:ios:3fc971bbbe24cd056f9dcc',
    messagingSenderId: '42486479397',
    projectId: 'smart-agri-7a6ed',
    storageBucket: 'smart-agri-7a6ed.appspot.com',
    iosBundleId: 'com.example.smartAgriApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDra81KEg99mb2lgaWB0YSY6rMUt8R52MU',
    appId: '1:42486479397:ios:3fc971bbbe24cd056f9dcc',
    messagingSenderId: '42486479397',
    projectId: 'smart-agri-7a6ed',
    storageBucket: 'smart-agri-7a6ed.appspot.com',
    iosBundleId: 'com.example.smartAgriApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHwhcbGKxovcSwuRnWawAGm8DekVDtrP4',
    appId: '1:42486479397:web:695139b38a4a63776f9dcc',
    messagingSenderId: '42486479397',
    projectId: 'smart-agri-7a6ed',
    authDomain: 'smart-agri-7a6ed.firebaseapp.com',
    storageBucket: 'smart-agri-7a6ed.appspot.com',
  );
}
